# Generated by Django 5.0.4 on 2024-11-27 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCUBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isMain', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('phone', models.DecimalField(decimal_places=0, max_digits=15)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCode', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('itemName', models.CharField(max_length=255)),
                ('itemBillName', models.CharField(max_length=255)),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isActive', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TCUSERNAME', models.CharField(max_length=255, unique=True)),
                ('TCPASSWORD', models.CharField(max_length=255)),
                ('TCGENDER', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('TCEMAIL', models.EmailField(max_length=254, unique=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('isPay', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('infoCUBranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.infocubranch')),
                ('infoProducts', models.ManyToManyField(related_name='history_products', to='myapp.infoproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
    ]
