# Generated by Django 5.0.4 on 2024-11-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_infocubranch_latitude_infocubranch_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infocubranch',
            old_name='isMain',
            new_name='isActive',
        ),
    ]
