# Generated by Django 5.0.4 on 2024-11-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_ismain_infocubranch_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='infocubranch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='infocubranch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
    ]
