# Generated by Django 5.0.4 on 2024-11-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_infoproduct_image_alter_infocubranch_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='infoProducts',
            field=models.ManyToManyField(help_text='Бараа', related_name='history_products', to='myapp.infoproduct'),
        ),
    ]
